#!/bin/sh

#
# Gradle start up script for UNIX generated by Gradle.
#

# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
      /*) app_path=$link ;;
      *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd -P "${APP_HOME:-./}" && printf '%s\n' "$PWD" ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$ *"
    echo
    exit 1
} >&2

# OS specific support
cygwin=false
msys=false
darwin=false
nonStop=false
case "$( uname )" in
  CYGWIN* )         cygwin=true ;;
  Darwin* )         darwin=true ;;
  MSYS* | MINGW* )  msys=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and 'java' command not found in your PATH."
    fi
fi

if [ "$cygwin" = "false" ] && [ "$darwin" = "false" ] && [ "$msys" = "false" ] ; then
    JAVACMD=$( which "$JAVACMD" 2>/dev/null ) || exit 1
fi

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
